### ISSUE TITLE
Authcore.button.reAuthNeeded

### ISSUE THREAD

**Issue by edmondyu** [likecoin/like-co#1323]
like.co/in/settings 偶爾會碰到這個錯誤。點擊沒反應（is it a label only?)。如果需要重新登入，係咪直接彈個視窗出嚟好啲？

![image](https://user-images.githubusercontent.com/17264698/70189586-a86ef580-172e-11ea-9607-8655e5ee55af.png)

**Comment by williamchong007** [comment]
應該係一入呢個 page 就會彈 authcore
而且撳落去都會彈
有冇 console error

**Comment by williamchong007** [comment]
locale key was fixed, and seems cannot reproduce for now
