### ISSUE TITLE
No verification mail is received

### ISSUE THREAD

**Issue by edmondyu** [likecoin/like-co#1328]
and is there a need to send this mail after oauth??  Or just under specific scenario, say the email+pwd registration case?

<img width="817" alt="7" src="https://user-images.githubusercontent.com/17264698/70485502-19951b00-1b2a-11ea-9fd1-51ec6b462236.png">

**Comment by williamchong007** [comment]
This only happen if the social platform thinks the email is not verified, and we do actually send the verification email when register
